version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    user: root
    ports:
      - "1883:1883"
      - "8883:8883"
    # Volumi rimossi completamente per permettere l'avvio manuale
    restart: always

  node-app:
    build: .
    container_name: mqtt-backend
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=8883
    # Volumi rimossi completamente
    restart: always