services:
  mqtt-server:
    image: eclipse-mosquitto:latest
    container_name: mqtt-server-cloud
    user: root
    ports:
      - "1883:1883"
      - "8883:8883"
    # Volumi rimossi completamente per permettere l'avvio manuale
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  node-app:
    build: .
    container_name: mqtt-backend
    depends_on:
      - mqtt-server
    environment:
      - MQTT_HOST=mqtt-server
      - MQTT_PORT=8883
    # Volumi rimossi completamente
    restart: always