version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      # Local fallback, Dokploy will use its own /files mount
      - ./certs:/files:ro
    command: mosquitto -c /files/mosquitto.conf
    restart: always

  node-app:
    build: .
    container_name: mqtt-backend
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker # Nome del servizio nel network docker
      - MQTT_PORT=8883
    volumes:
      - ./certs:/usr/src/app/certs:ro
    restart: always